# -*- coding: utf-8 -*-
"""collect_relay_innings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tbvOXNGKktr6sxTrdPtyBUWtAjKafjHh
"""

# collect_relay_innings.py
from __future__ import annotations
import json
import time
import os
from typing import Dict, Any

import requests

GAME_ID = "20250922OBSK02025"
BASE_URL = f"https://api-gw.sports.naver.com/schedule/games/{GAME_ID}/relay"
OUT_DIR = os.path.join("data", "raw")

HEADERS = {
    "User-Agent": "Mozilla/5.0",
    "Accept": "application/json, text/plain, */*",
    "Referer": "https://m.sports.naver.com/",
}

def ensure_dir(p: str):
    os.makedirs(p, exist_ok=True)

def fetch_inning(inning: int) -> Dict[str, Any]:
    url = f"{BASE_URL}?inning={inning}"
    r = requests.get(url, headers=HEADERS, timeout=20)
    r.raise_for_status()
    return r.json()

def save_json(path: str, obj: Dict[str, Any]):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False)

def main():
    ensure_dir(OUT_DIR)

    for inn in range(1, 10):
        out_path = os.path.join(OUT_DIR, f"{GAME_ID}_inning{inn:02d}.json")
        print(f"[GET] inning={inn} -> {out_path}")

        data = fetch_inning(inn)
        save_json(out_path, data)

        # 너무 빠르게 치면 막힐 수 있어서 최소 딜레이
        time.sleep(0.3)

    print("DONE")

if __name__ == "__main__":
    main()